src/Entity/Pedido.php
<?php

namespace App\Entity;

use App\Entity\Traits;
use App\Repository\PedidoRepository;
use App\Entity\Traits\Auditoria;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * Grupo
 *
 * @ORM\Table(name="pedido")
 * @ORM\Entity(repositoryClass=PedidoRepository::class)
 *
 * @Gedmo\SoftDeleteable(fieldName="fechaBaja")
 */
class Pedido {

    use Auditoria;

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    protected $id;

    /**
     * @ORM\OneToMany(targetEntity=PedidoProducto::class, mappedBy="pedido", cascade={"all"})
     * @ORM\OrderBy({"id" = "DESC"})
     */
    private $pedidosProductos;

    /**
     * @ORM\ManyToOne(targetEntity=Usuario::class, inversedBy="pedidos")
     * @ORM\JoinColumn(name="id_cliente", referencedColumnName="id")
     */
    private $cliente;

    /**
     * @ORM\Column(name="observacion", type="string", length=255, nullable=true)
     */
    private $observacion;

    /**
     * @ORM\OneToOne(targetEntity=CuentaCorrientePedido::class, inversedBy="pedido")
     * @ORM\JoinColumn(name="id_cuenta_corriente_pedido", referencedColumnName="id")
     */
    private $cuentaCorrientePedido;

    public function __construct()
    {
        $this->historicoEstados = new ArrayCollection();
        $this->pedidosProductos = new ArrayCollection();
    }

    public function __toString(): string
    {
        return 'Pedido N° '.$this->getId(). ' Fecha Pedido: '.$this->getFechaCreacion()->format('d/m/Y');
    }

    public function getNombreCorto(): string
    {
        return 'Pedido N° '.$this->getId();
    }


    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param int $id
     */
    public function setId(int $id): void
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getPedidosProductos()
    {
        return $this->pedidosProductos;
    }

    /**
     * @param mixed $pedidosProductos
     */
    public function setPedidosProductos($pedidosProductos): void
    {
        $this->pedidosProductos = $pedidosProductos;

        foreach ($pedidosProductos as $pedidoProducto){
            $pedidoProducto->setPedido($this);
        }
    }

    /**
     * @return mixed
     */
    public function addPedidosProductos($pedidoProducto)
    {
        if (!$this->pedidosProductos->contains($pedidoProducto)) {
            $this->pedidosProductos[] = $pedidoProducto;
            $pedidoProducto->setPedido($this);
        }

        return $this;
    }

    /**
     * @return mixed
     */
    public function getCliente()
    {
        return $this->cliente;
    }

    /**
     * @param mixed $cliente
     */
    public function setCliente($cliente): void
    {
        $this->cliente = $cliente;
    }

    /**
     * @return mixed
     */
    public function getHistoricoEstados()
    {
        return $this->historicoEstados;
    }

    /**
     * @param mixed $historicoEstados
     */
    public function setHistoricoEstados($historicoEstados): void
    {
        $this->historicoEstados = $historicoEstados;
    }

    /**
     * @return mixed
     */
    public function getEstado()
    {
        return $this->estado;
    }

    /**
     * @param mixed $estado
     */
    public function setEstado($estado): void
    {
        $this->estado = $estado;
    }



    /**
     * @return mixed
     */
    public function getObservacion()
    {
        return $this->observacion;
    }

    /**
     * @param mixed $observacion
     */
    public function setObservacion($observacion): void
    {
        $this->observacion = $observacion;
    }

    public function addPedidosProducto(PedidoProducto $pedidosProducto): static
    {
        if (!$this->pedidosProductos->contains($pedidosProducto)) {
            $this->pedidosProductos->add($pedidosProducto);
            $pedidosProducto->setPedido($this);
        }

        return $this;
    }

    public function removePedidosProducto(PedidoProducto $pedidosProducto): static
    {
        if ($this->pedidosProductos->removeElement($pedidosProducto)) {
            // set the owning side to null (unless already changed)
            if ($pedidosProducto->getPedido() === $this) {
                $pedidosProducto->setPedido(null);
            }
        }

        return $this;
    }

    /**
     * @return mixed
     */
    public function getCuentaCorrientePedido()
    {
        return $this->cuentaCorrientePedido;
    }

    /**
     * @param mixed $cuentaCorrientePedido
     */
    public function setCuentaCorrientePedido($cuentaCorrientePedido): void
    {
        $this->cuentaCorrientePedido = $cuentaCorrientePedido;
    }

    public function getAdelanto(){
        return $this->getCuentaCorrientePedido()->getSaldo();
    }

    public function getTieneMovimientos(){
        return (sizeof($this->getCuentaCorrientePedido()->getMovimientos()) > 0);
    }

    public function getCodigo(){
        return str_pad($this->id, 6, "0", STR_PAD_LEFT);
    }

}

src/Controller/OrdenCargaController.php
<?php

namespace App\Controller;

use App\Entity\Constants\ConstanteEstadoEntrega;
use App\Entity\Constants\ConstanteTipoConsulta;
use App\Entity\Entrega;
use App\Entity\EstadoEntrega;
use DateTime;
use Doctrine\ORM\Query\ResultSetMapping;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/orden_carga")
 * @IsGranted("ROLE_ORDEN_CARGA")
 */
class OrdenCargaController extends BaseController
{

    /**
     * @Route("/", name="ordencarga_index", methods={"GET"})
     * @Template("orden_carga/index.html.twig")
     * @IsGranted("ROLE_ORDEN_CARGA")
     */
    public function index(): array
    {
        $bread = $this->baseBreadcrumbs;
        $bread['OrdenCarga'] = null;

        return array(
            'breadcrumbs' => $bread,
            'page_title' => 'OrdenCarga'
        );
    }

    /**
     *
     * @Route("/index_table/", name="orden_carga_table", methods={"GET|POST"})
     * @IsGranted("ROLE_ORDEN_CARGA")
     */
    public function indexTableAction(Request $request): Response {

        $entityTable = 'view_orden_carga';

        $rsm = new ResultSetMapping();

        $rsm->addScalarResult('id', 'id');
        $rsm->addScalarResult('title', 'title');
        $rsm->addScalarResult('fecha', 'fecha');
        $rsm->addScalarResult('className', 'className');
        $rsm->addScalarResult('estado', 'estado');
        $rsm->addScalarResult('colorEstado', 'colorEstado');
        $rsm->addScalarResult('idEstado', 'idEstado');
        $rsm->addScalarResult('cliente', 'cliente');

        $renderPage = "orden_carga/index_table.html.twig";
        return parent::baseIndexTableAction($request, [], $entityTable, ConstanteTipoConsulta::VIEW, $rsm, $renderPage);
    }

    /**
     * @Route("/{id}", name="orden_carga_show", methods={"GET","POST"})
     * @Template("orden_carga/show.html.twig")
     */
    public function showPedidoProductoAction($id) {

        $em = $this->doctrine->getManager();

        /* @var $entrega Entrega */
        $entrega = $em->getRepository('App\Entity\Entrega')->find($id);

        if (!$entrega) {
            throw $this->createNotFoundException('No se puede encontrar la entrega.');
        }

        return array(
            'entity' => $entrega,
            'page_title' => 'Orden de carga'
        );
    }

    /**
     *
     * @Route("/cambiar_fecha_orden_carga/", name="cambiar_fecha_orden_carga", methods={"POST"})
     * @IsGranted("ROLE_ORDEN_CARGA")
     */
    public function cambiarFechaOrdenCarga(Request $request){

        $fechaNuevaParam = $request->get('fechaNueva');
        $idEntrega = $request->get('idEntrega');
        $datetime = new DateTime();
        $nuevaFecha = $datetime->createFromFormat('Y-m-d', $fechaNuevaParam);

        $em = $this->doctrine->getManager();
        /* @var $entrega Entrega */
        $entrega = $em->getRepository('App\Entity\Entrega')->find($idEntrega);
        $entrega->setFechaEntrega($nuevaFecha);
        $em->flush();

        $message = 'Se modifico correctamente la fecha de la Entrega N°'.$entrega->getId();
        $result = array(
            'status' => 'OK',
            'message' => $message
        );

        return new JsonResponse($result);

    }

    /**
     *
     * @Route("/entregar/", name="entregar_orden_carga", methods={"POST"})
     * @IsGranted("ROLE_ORDEN_CARGA")
     */
    public function guardarOrdenCarga(Request $request){
        
        $idEntrega = $request->get('idEntrega');

        $em = $this->doctrine->getManager();

        /* @var $entrega Entrega */
        $entrega = $em->getRepository('App\Entity\Entrega')->find($idEntrega);

        if ($entrega->getRemito() != null) {
            $estado = $em->getRepository(EstadoEntrega::class)->findOneByCodigoInterno(ConstanteEstadoEntrega::ENTREGADO_CON_REMITO);
        }else{
            $estado = $em->getRepository(EstadoEntrega::class)->findOneByCodigoInterno(ConstanteEstadoEntrega::ENTREGADO_SIN_REMITO);
        }

        $this->estadoService->cambiarEstadoEntrega($entrega, $estado, 'ENTREGADO.');
        $entrega->setEntregado(true);
        $entrega->setFechaEntrega(
            (new \DateTime())->setTime(23, 59, 0)
        );

        $em->flush();

        $message = 'Pedido entregado correctamente';
        $result = array(
            'status' => 'OK',
            'message' => $message
        );

        return new JsonResponse($result);

    }
}

templates/orden_carga/index.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}

    {{ parent() }}

    <link href="{{ asset(plugins_path ~ 'custom/datatables/datatables.bundle.css') }}" rel="stylesheet" type="text/css"/>
    <link href="{{ asset(plugins_path ~ 'custom/fullcalendar/fullcalendar.bundle.css') }}" rel="stylesheet" type="text/css"/>

    <style>
    </style>

{% endblock %}

{% block body %}
    <div class="card card-custom">
        <div class="card-header">
            <div class="card-title">
                <h3 class="card-label">
                    Orden de carga
                </h3>
            </div>
            <div class="card-toolbar">
                <a href="#" class="btn btn-light-primary font-weight-bold" id="btn-fscreen">
                    <i class="fas fa-expand"></i>
                </a>
            </div>
        </div>
        <div class="card-body" id="fScreen">
            <div id="kt_calendar"></div>
        </div>
    </div>
{% endblock %}

{% block javascripts %}

    {{ parent() }}
    <script src="{{ asset(__PREFIX_JAVASCRIPT__ ~ 'app/ordencarga/index.js') }}" ></script>
    <script src="{{ asset(__PREFIX_JAVASCRIPT__ ~ 'app/pedidoproducto/observacion.js') }}" ></script>
    <script src="{{ asset(plugins_path ~ 'custom/fullcalendar/fullcalendar.bundle.js') }}"></script>

    <script>
        $('#btn-fscreen').on('click', function(){
            /*var elem = document.getElementById("kt_body");
            req = elem.requestFullScreen || elem.webkitRequestFullScreen || elem.mozRequestFullScreen;
            req.call(elem);
             */
            toggleFullScreen();
        });

        function toggleFullScreen() {
            if (!document.fullscreenElement &&    // alternative standard method
                !document.mozFullScreenElement && !document.webkitFullscreenElement && !document.msFullscreenElement ) {  // current working methods
                if (document.documentElement.requestFullscreen) {
                    document.documentElement.requestFullscreen();
                } else if (document.documentElement.msRequestFullscreen) {
                    document.documentElement.msRequestFullscreen();
                } else if (document.documentElement.mozRequestFullScreen) {
                    document.documentElement.mozRequestFullScreen();
                } else if (document.documentElement.webkitRequestFullscreen) {
                    document.documentElement.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);
                }
            } else {
                if (document.exitFullscreen) {
                    document.exitFullscreen();
                } else if (document.msExitFullscreen) {
                    document.msExitFullscreen();
                } else if (document.mozCancelFullScreen) {
                    document.mozCancelFullScreen();
                } else if (document.webkitExitFullscreen) {
                    document.webkitExitFullscreen();
                }
            }
        }
    </script>
{% endblock %}

templates/orden_carga/index_table.html.twig
{% autoescape false %}
    [
    {% for entity in entities %}
        {
        "id": "{{ entity.id }}",
        "estado": "{{ entity.estado }}",
        "colorEstado": "{{ entity.colorEstado }}",
        "idEstado": "{{ entity.idEstado }}",
        "cliente": "{{ entity.cliente }}",
        "title": "{{ entity.title|default('-') }}",
        "start": "{{ entity.fecha is not null ? entity.fecha|date('Y-m-d\\TH:i') : '' }}",
        "end": "{{ entity.fecha is not null
            ? entity.fecha|date_modify('+1 minute')|date('Y-m-d\\TH:i')
            : ''
            }}",

        "href":  "{{ path( "orden_carga_show", { 'id': entity.id }) }}",
        "className": "{{ entity.className|default('fc-event-danger fc-event-solid-danger') }}"
        }
        {{ (loop.last ? '' : ',') }}
    {% endfor %}
    ]

{% endautoescape %}

templates/orden_carga/show.html.twig
{% if entity is defined %}
    <div class="row">
        <div class="modal-body">
            <div class="row">
                <div class="col-md-4">
                    <div class="d-flex align-items-center mb-10">
                        <div class="symbol symbol-40 symbol-light-primary mr-5">
                            <span class="symbol-label">
                                <span class="svg-icon svg-icon-xl svg-icon-primary">
                                    <i class="fas fa-user icon-2x text-dark"></i>
                                </span>
                            </span>
                        </div>
                        <div class="d-flex flex-column font-weight-bold">
                            <label class="text-dark text-hover-primary mb-1 font-size-lg">Cliente</label>
                            <span class="text-muted">{{ entity.clienteEntrega.nombreCorto }}</span>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="d-flex align-items-center mb-10">
                        <div class="symbol symbol-40 symbol-light-primary mr-5">
                            <span class="symbol-label">
                                <span class="svg-icon svg-icon-xl svg-icon-primary">
                                    <i class="fas fa-user icon-2x text-dark"></i>
                                </span>
                            </span>
                        </div>
                        <div class="d-flex flex-column font-weight-bold">
                            <label class="text-dark text-hover-primary mb-1 font-size-lg">Direccion</label>
                            <span class="text-muted">{{ entity.clienteEntrega.domicilio|default('-') }}</span>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="d-flex align-items-center mb-10">
                        <div class="symbol symbol-40 symbol-light-primary mr-5">
                            <span class="symbol-label">
                                <span class="svg-icon svg-icon-xl svg-icon-primary">
                                    <i class="la la-file-alt icon-2x text-dark"></i>
                                </span>
                            </span>
                        </div>
                        <div class="d-flex flex-column font-weight-bold">
                            <span class="label label-inline font-weight-bold estado {{ entity.estado.color|default('') }}" style="padding: 20px;">{{ entity.estado.nombre|default('') }}</span>
                        </div>
                    </div>
                </div>
            </div>
            {% set totalBandejas = 0 %}
            {% set mostrarMesada2 = false %}

            {% for entregaProducto in entity.entregasProductos %}
                {% set totalBandejas = totalBandejas + entregaProducto.cantidadBandejas %}

                {% if entregaProducto.pedidoProducto.mesadaDos %}
                    {% set mostrarMesada2 = true %}
                {% endif %}
            {% endfor %}
            <div class="row">
                <div class="col-12">
                    <div class="card-body pt-0">
                        <div class="table-responsive">
                            <table class="table table-hover table-striped align-middle">
                                <thead class="thead-light">
                                <tr>
                                    <th>
                                        Productos
                                        <span class="text-muted font-size-sm ml-2">
                                            ({{ entity.entregasProductos|length }})
                                        </span>
                                    </th>
                                    <th class="text-center">Orden</th>
                                    <th class="text-center">Mesada 1</th>
                                    {% if mostrarMesada2 %}
                                        <th class="text-center">Mesada 2</th>
                                    {% endif %}
                                    <th class="text-center">Bandejas
                                        <span class="text-muted font-size-sm ml-2">
                                            ({{ totalBandejas }})
                                        </span>
                                    </th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for entregaProducto in entity.entregasProductos %}
                                    {% set pedidoProducto = entregaProducto.pedidoProducto %}
                                    <tr>
                                        <td>
                                            <div class="d-flex align-items-center">
                                                <span class="symbol symbol-35 symbol-light-success mr-3">
                                                    <span class="symbol-label">
                                                        <i class="fas fa-seedling text-success"></i>
                                                    </span>
                                                </span>
                                                <span class="font-weight-bold text-dark">
                                                    <span class="label label-inline font-weight-bold" style="background-color:{{ pedidoProducto.tipoProducto.color }};color:#fff; padding: 20px">{{ pedidoProducto.tipoVariedad }} (X{{ pedidoProducto.tipoBandeja }})</span>
                                                </span>
                                            </div>
                                        </td>

                                        <td class="text-center" style="color:{{ pedidoProducto.tipoProducto.color }}; font-weight: bold">
                                            {{ pedidoProducto.numeroOrdenCompleto|default('-') }}
                                        </td>

                                        <td class="text-center">
                                            {{ pedidoProducto.mesadaUno ?: '-' }}
                                        </td>

                                        {% if mostrarMesada2 %}
                                            <td class="text-center">
                                                {{ pedidoProducto.mesadaDos ?: '-' }}
                                            </td>
                                        {% endif %}

                                        <td class="text-center">
                                            <span class="badge badge-pill badge-primary font-weight-bold px-4 py-2">
                                                {{ entregaProducto.cantidadBandejas|default(0) }}
                                            </span>
                                        </td>
                                    </tr>
                                {% else %}
                                    <tr>
                                        <td colspan="5" class="text-center py-10">
                                            <i class="fas fa-box-open fa-2x text-muted mb-3"></i>
                                            <div class="text-muted font-weight-bold">
                                                No hay productos en esta entrega
                                            </div>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endif  %}