src/Entity/Pedido.php
<?php

namespace App\Entity;

use App\Entity\Traits;
use App\Repository\PedidoRepository;
use App\Entity\Traits\Auditoria;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * Grupo
 *
 * @ORM\Table(name="pedido")
 * @ORM\Entity(repositoryClass=PedidoRepository::class)
 *
 * @Gedmo\SoftDeleteable(fieldName="fechaBaja")
 */
class Pedido {

    use Auditoria;

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    protected $id;

    /**
     * @ORM\OneToMany(targetEntity=PedidoProducto::class, mappedBy="pedido", cascade={"all"})
     * @ORM\OrderBy({"id" = "DESC"})
     */
    private $pedidosProductos;

    /**
     * @ORM\ManyToOne(targetEntity=Usuario::class, inversedBy="pedidos")
     * @ORM\JoinColumn(name="id_cliente", referencedColumnName="id")
     */
    private $cliente;

    /**
     * @ORM\Column(name="observacion", type="string", length=255, nullable=true)
     */
    private $observacion;

    /**
     * @ORM\OneToOne(targetEntity=CuentaCorrientePedido::class, inversedBy="pedido")
     * @ORM\JoinColumn(name="id_cuenta_corriente_pedido", referencedColumnName="id")
     */
    private $cuentaCorrientePedido;

    public function __construct()
    {
        $this->historicoEstados = new ArrayCollection();
        $this->pedidosProductos = new ArrayCollection();
    }

    public function __toString(): string
    {
        return 'Pedido N° '.$this->getId(). ' Fecha Pedido: '.$this->getFechaCreacion()->format('d/m/Y');
    }

    public function getNombreCorto(): string
    {
        return 'Pedido N° '.$this->getId();
    }


    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param int $id
     */
    public function setId(int $id): void
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getPedidosProductos()
    {
        return $this->pedidosProductos;
    }

    /**
     * @param mixed $pedidosProductos
     */
    public function setPedidosProductos($pedidosProductos): void
    {
        $this->pedidosProductos = $pedidosProductos;

        foreach ($pedidosProductos as $pedidoProducto){
            $pedidoProducto->setPedido($this);
        }
    }

    /**
     * @return mixed
     */
    public function addPedidosProductos($pedidoProducto)
    {
        if (!$this->pedidosProductos->contains($pedidoProducto)) {
            $this->pedidosProductos[] = $pedidoProducto;
            $pedidoProducto->setPedido($this);
        }

        return $this;
    }

    /**
     * @return mixed
     */
    public function getCliente()
    {
        return $this->cliente;
    }

    /**
     * @param mixed $cliente
     */
    public function setCliente($cliente): void
    {
        $this->cliente = $cliente;
    }

    /**
     * @return mixed
     */
    public function getHistoricoEstados()
    {
        return $this->historicoEstados;
    }

    /**
     * @param mixed $historicoEstados
     */
    public function setHistoricoEstados($historicoEstados): void
    {
        $this->historicoEstados = $historicoEstados;
    }

    /**
     * @return mixed
     */
    public function getEstado()
    {
        return $this->estado;
    }

    /**
     * @param mixed $estado
     */
    public function setEstado($estado): void
    {
        $this->estado = $estado;
    }



    /**
     * @return mixed
     */
    public function getObservacion()
    {
        return $this->observacion;
    }

    /**
     * @param mixed $observacion
     */
    public function setObservacion($observacion): void
    {
        $this->observacion = $observacion;
    }

    public function addPedidosProducto(PedidoProducto $pedidosProducto): static
    {
        if (!$this->pedidosProductos->contains($pedidosProducto)) {
            $this->pedidosProductos->add($pedidosProducto);
            $pedidosProducto->setPedido($this);
        }

        return $this;
    }

    public function removePedidosProducto(PedidoProducto $pedidosProducto): static
    {
        if ($this->pedidosProductos->removeElement($pedidosProducto)) {
            // set the owning side to null (unless already changed)
            if ($pedidosProducto->getPedido() === $this) {
                $pedidosProducto->setPedido(null);
            }
        }

        return $this;
    }

    /**
     * @return mixed
     */
    public function getCuentaCorrientePedido()
    {
        return $this->cuentaCorrientePedido;
    }

    /**
     * @param mixed $cuentaCorrientePedido
     */
    public function setCuentaCorrientePedido($cuentaCorrientePedido): void
    {
        $this->cuentaCorrientePedido = $cuentaCorrientePedido;
    }

    public function getAdelanto(){
        return $this->getCuentaCorrientePedido()->getSaldo();
    }

    public function getTieneMovimientos(){
        return (sizeof($this->getCuentaCorrientePedido()->getMovimientos()) > 0);
    }

    public function getCodigo(){
        return str_pad($this->id, 6, "0", STR_PAD_LEFT);
    }

}

src/Entity/Remito.php
<?php

namespace App\Entity;

use App\Entity\Traits;
use App\Entity\Traits\Auditoria;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * Grupo
 *
 * @ORM\Table(name="remito")
 * @ORM\Entity
 * @Gedmo\SoftDeleteable(fieldName="fechaBaja")
 */
class Remito {

    use Auditoria;

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    protected $id;

    /**
     * @ORM\ManyToOne(targetEntity=TipoDescuento::class)
     * @ORM\JoinColumn(name="id_tipo_descuento", referencedColumnName="id", nullable=true)
     */
    private $tipoDescuento;

    /**
     * @ORM\Column(name="cantidad_descuento", type="integer", nullable=true)
     */
    private $cantidadDescuento;

    /**
     * @ORM\Column(name="motivo_descuento", type="string", length=255, nullable=true)
     */
    private $motivoDescuento;

    /**
     * @ORM\OneToMany(targetEntity=EstadoRemitoHistorico::class, mappedBy="remito", cascade={"all"})
     * @ORM\OrderBy({"fecha" = "DESC", "id" = "DESC"})
     */
    private $historicoEstados;

    /**
     * @ORM\ManyToOne(targetEntity=EstadoRemito::class)
     * @ORM\JoinColumn(name="id_estado_remito", referencedColumnName="id", nullable=false)
     */
    private mixed $estado;


    /**
     * @ORM\OneToMany(targetEntity=Pago::class, mappedBy="remito", cascade={"all"})
     * @ORM\OrderBy({"fechaCreacion" = "ASC"})
     */
    private $pagos;

    /**
     * @ORM\OneToMany(targetEntity=Entrega::class, mappedBy="remito", cascade={"all"})
     * @ORM\OrderBy({"id" = "DESC"})
     */
    private $entregas;

    /**
     * @ORM\ManyToOne(targetEntity=Usuario::class, inversedBy="remitos")
     * @ORM\JoinColumn(name="id_cliente", referencedColumnName="id", nullable=false)
     */
    private $cliente;

    /**
     * @ORM\Column(name="saldo_cuenta_corriente", type="decimal", precision=10, scale=2, nullable=true)
     */
    private $saldoCuentaCorriente;

    /**
     * @ORM\Column(name="total_deuda", type="decimal", precision=10, scale=2, nullable=true)
     */
    private $totalDeuda;

    public function __construct()
    {
        $this->entregas = new ArrayCollection();
        $this->historicoEstados = new ArrayCollection();
        $this->pagos = new ArrayCollection();
    }

    public function __toString(): string
    {
        return 'Remito N° '.$this->getId();
    }


    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    public function getCodigo(){
        return str_pad($this->id, 6, "0", STR_PAD_LEFT);
    }

    /**
     * @param int $id
     */
    public function setId(int $id): void
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getCliente()
    {
        return $this->cliente;
    }

    /**
     * @param mixed $cliente
     */
    public function setCliente($cliente): void
    {
        $this->cliente = $cliente;
    }

    public function getTotalSinDescuento(){
        $total = 0.00;
        foreach ($this->getEntregas() as $entrega) {
            foreach ($entrega->getEntregasProductos() as $entregaProducto) {
                $total += $entregaProducto->getPrecioSubTotal();
            }
        }
        return $total;
    }

    public function getTotalConDescuento(){
        $total = $this->getTotalSinDescuento();
        if ($this->getTipoDescuento() != null) {
            switch ($this->getTipoDescuento()->getCodigoInterno()) {
                case 1:
                    $total -= $this->getCantidadDescuento();
                    break;
                case 2:
                    $total -= (($total * $this->getCantidadDescuento()) / 100);
                    break;
            }
        }
        return $total;
    }

    public function getMontoDescuento($totalSinDescuento = null){
        $totalSinDescuento = ($totalSinDescuento == null ? $this->getTotalSinDescuento() : $totalSinDescuento);
        $descuento = '';
        if ($this->getTipoDescuento() != null) {
            switch ($this->getTipoDescuento()->getCodigoInterno()) {
                case 1:
                    $descuento = $this->getCantidadDescuento();
                    break;
                case 2:
                    $descuento = (($totalSinDescuento * $this->getCantidadDescuento()) / 100);
                    break;
            }
        }

        return $descuento;
    }

    public function getTipoDescuentoString(){
        $tipoDescuento = '';
        if ($this->getTipoDescuento() != null) {
            switch ($this->getTipoDescuento()->getCodigoInterno()) {
                case 1:
                    $tipoDescuento = '-';
                    break;
                case 2:
                    $tipoDescuento = '('.$this->getCantidadDescuento().'%) -';
                    break;
            }
        }

        return $tipoDescuento;
    }

    /**
     * @return mixed
     */
    public function getTipoDescuento()
    {
        return $this->tipoDescuento;
    }

    /**
     * @param mixed $tipoDescuento
     */
    public function setTipoDescuento($tipoDescuento): void
    {
        $this->tipoDescuento = $tipoDescuento;
    }

    /**
     * @return mixed
     */
    public function getCantidadDescuento()
    {
        return $this->cantidadDescuento;
    }

    /**
     * @param mixed $cantidadDescuento
     */
    public function setCantidadDescuento($cantidadDescuento): void
    {
        $this->cantidadDescuento = $cantidadDescuento;
        /*if ($this->getTipoDescuento() != null) {
            if ($this->getTipoDescuento()->getCodigoInterno() == 1) {
                $cantidadDescuento = $this->getCantidadDescuento();
                foreach ($this->getEntregas() as $entrega) {
                    foreach ($entrega->getEntregasProductos() as $entregaProducto) {
                        if ($cantidadDescuento > 0) {
                            $descontar = $cantidadDescuento >= $entregaProducto->getPrecioSubTotal() ? $entregaProducto->getPrecioSubTotal() : $cantidadDescuento;
                            $entregaProducto->setCantidadDescuentoFijo($descontar);
                            $cantidadDescuento -= $descontar;
                        }
                    }
                }
            }
        }*/
    }

    /**
     * @return string|null
     */
    public function getMotivoDescuento(): ?string
    {
        return $this->motivoDescuento;
    }

    /**
     * @param string|null $motivoDescuento
     * @return $this
     */
    public function setMotivoDescuento(?string $motivoDescuento): self
    {
        $this->motivoDescuento = $motivoDescuento;
        return $this;
    }

    /**
     * @return Collection|EstadoRemitoHistorico[]
     */
    public function getHistoricoEstados(): Collection
    {
        return $this->historicoEstados;
    }

    /**
     * @param mixed $historicoEstados
     */
    public function setHistoricoEstados($historicoEstados): void
    {
        $this->historicoEstados = $historicoEstados;
    }

    public function getEstado(): mixed
    {
        return $this->estado;
    }

    public function setEstado(mixed $estado): void
    {
        $this->estado = $estado;
    }

    public function addHistoricoEstado(EstadoRemitoHistorico $historicoEstado): self {
        if (!$this->historicoEstados->contains($historicoEstado)) {
            $this->historicoEstados[] = $historicoEstado;
            $historicoEstado->setRemito($this);
        }

        return $this;
    }

    public function removeHistoricoEstado(EstadoRemitoHistorico $historicoEstado): self {
        if ($this->historicoEstados->removeElement($historicoEstado)) {
            // set the owning side to null (unless already changed)
            if ($historicoEstado->getRemito() === $this) {
                $historicoEstado->setRemito(null);
            }
        }

        return $this;
    }

    public function getPagos()
    {
        return $this->pagos;
    }

    public function setPagos(ArrayCollection $pagos): void
    {
        $this->pagos = $pagos;
    }

    /**
     * @return mixed
     */
    public function addPago(Pago $pago)
    {
        if (!$this->pagos->contains($pago)) {
            $this->pagos[] = $pago;
            $pago->setRemito($this);
        }

        return $this;
    }

    /**
     * @return mixed
     */
    public function getPendiente()
    {
        $pendiente = $this->getTotalConDescuento();
        foreach ($this->pagos as $pago) {
            $pendiente -=$pago->getMonto();
        }
        return $pendiente;
    }

    public function addEntrega(Entrega $entrega): self {
        if (!$this->entregas->contains($entrega)) {
            $this->entregas[] = $entrega;
            $entrega->setRemito($this);
        }

        return $this;
    }

    public function removeEntrega(Entrega $entrega): self {
        if ($this->entregas->removeElement($entrega)) {
            // set the owning side to null (unless already changed)
            if ($entrega->getRemito() === $this) {
                $entrega->setRemito(null);
            }
        }

        return $this;
    }

    /**
     * @return mixed
     */
    public function getEntregas()
    {
        return $this->entregas;
    }

    public function getAdelanto()
    {
        $adelanto = 0;
        $pedidosVistos = [];

        foreach ($this->entregas as $entrega) {
            foreach ($entrega->getEntregasProductos() as $entregaProducto) {
                $pedido = $entregaProducto->getPedidoProducto()->getPedido();
                $pedidoId = $pedido->getId();

                if (!isset($pedidosVistos[$pedidoId])) {
                    $adelanto += $pedido->getAdelanto();
                    $pedidosVistos[$pedidoId] = true;
                }
            }
        }

templates/situacion_cliente/empresa/filtros.html.twig
<div class="portlet light bordered portlet-nivel-1" style="padding: 5px 10px; margin-left: 30px;border-radius: 5px;background-color: #E1F0FF">
    <div class="row">
        <div class="col-md-7">
            <label for="reporte_filtro_cliente" class="control-label">BUSCAR RAZON SOCIAL</label>
            <select class="choice form-control datatable-input" id="reporte_filtro_cliente" name="reporte_filtro[cliente]">
                <option value="">TODOS</option>
                {% for razonSocial in razonSocialSelect %}
                    <option value="{{ razonSocial.id }}"> {{ razonSocial.nombre }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="col-md-5 padding-top-25">
            <button class="btn btn-primary btn-primary--icon" id="kt_search">
                <span>
                    <i class="la la-search"></i>
                    <span>Buscar</span>
                </span>
            </button>
            <button class="btn btn-secondary btn-secondary--icon" id="kt_reset">
                <span>
                    <i class="la la-close"></i>
                    <span>Limpiar</span>
                </span>
            </button>
        </div>
    </div>
</div>

templates/situacion_cliente/empresa/show.html.twig
{% extends 'base.html.twig' %}

{% import 'app/_macro_show.html.twig' as macro_show %}
{% block stylesheets %}

    {{ parent() }}

    <style type="text/css">


        .card.card-detail .card-header {
            padding: 15px;
            background-color: #f5f5f5;
        }

        .card.card-detail {
            margin-bottom: 20px;
        }
        .card.card-custom{
            box-shadow: 0px 0px 20px 0px gray;
        }

        .select2-results__options .select2-results__option[aria-disabled=true] {
            display: none;
        }

    </style>
{% endblock stylesheets %}

{% block body %}


    <div class="row">
        {% include 'situacion_cliente/empresa/show_tiles.html.twig' %}
    </div>

    <div class="row">
        <div class="col-md-4 padding-1">
            {% include 'situacion_cliente/empresa/show_pedidos.html.twig' %}
        </div>
        <div class="col-md-4 padding-1">
            {% include 'situacion_cliente/empresa/show_reservas.html.twig' %}
        </div>
        <div class="col-md-4 padding-1">
            {% include 'situacion_cliente/empresa/show_entregas.html.twig' %}
        </div>
        <div class="col-md-4 padding-1">
            {% include 'situacion_cliente/empresa/show_remitos.html.twig' %}
        </div>
        <div class="col-md-4 padding-1">
            {% include 'situacion_cliente/empresa/show_pagos.html.twig' %}
        </div>
        <div class="col-md-4 padding-1">
            {% include 'situacion_cliente/empresa/show_adelantos.html.twig' %}
        </div>
        <div class="col-md-4 padding-1">
            {% include 'situacion_cliente/empresa/show_movimientos.html.twig' %}
        </div>

        <div class="col-md-4 padding-1">
            {% include 'situacion_cliente/empresa/show_clientes.html.twig' %}
        </div>




    </div>



    <div class="card-footer d-flex justify-content-between">
        <a href="{{ path('situacioncliente_index') }}" class="btn btn-light-dark font-weight-bold">Volver al listado</a>
    </div>

{% endblock %}

{% block javascripts %}

    {{ parent() }}

    <script src="{{ asset(__PREFIX_JAVASCRIPT__ ~ 'app/situacioncliente/show.js') }}" ></script>

    <script>
        var __ID_CUENTA_CORRIENTE__ = {{ razonSocial.id }};
        var __ID_USUARIO__ = {{ razonSocial.id }};
    </script>

{% endblock %}

templates/situacion_cliente/empresa/show_adelantos.html.twig
<div class="card card-detail">
    <div class="card-header d-flex justify-content-between align-items-center padding-10">
        <div class="card-title mb-0">
            <h4 class="card-label mb-0">Adelantos</h4>
        </div>
        <div class="card-toolbar">
            <a href="{{ path('imprimir_comprobante_movimiento_todos',{id: razonSocial.id}) }}" target="_blank"
               class="btn btn-light-primary btn-icon btn-sm blue" title="Imprimir comprobante" style="width: 150px; float: right">
                <i class="fa fa-file-pdf text-white">&nbsp;</i> Imprimir todos
            </a>
        </div>
    </div>
    <div class="card-body padding-20">
        <div class="row">
            <div class="tab-content" style="width: 100%;">
                <div class="tab-pane active" id="portlet_pedido_listado">
                    <div class="portlet-body padding-0">
                        <div class="row">
                            <div class="col-md-12">
                                {% if razonSocial.tieneMovimientos %}
                                    <div class="table-scrollable" style="border: none;overflow-y:scroll; height:400px;">
                                        <table class="table table-striped table-bordered table-advance table-hover" style="border: 1px solid #ddd;">
                                            <thead>
                                            <tr>
                                                <th class="text-center nowrap">Monto</th>
                                                <th class="text-center nowrap">Modo de pago</th>
                                                <th class="text-center nowrap">Descripción</th>
                                                <th class="text-center nowrap">Pedido/Reserva</th>
                                                <th class="text-center nowrap">Fecha</th>
                                                <th class="text-center nowrap"></th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            {% for reserva in razonSocial.reservas %}
                                                {% for movimiento in reserva.cuentaCorrienteReserva.movimientos %}
                                                    <tr>
                                                        <td class="v-middle nowrap text-center">
                                                            {{ movimiento.monto|money_format }}
                                                        </td>
                                                        <td class="v-middle nowrap text-center">
                                                            {{ movimiento.modoPago|default('-') }}
                                                        </td>
                                                        <td class="v-middle nowrap text-center">
                                                            {{ movimiento.descripcion|default('-') }}
                                                        </td>
                                                        <td class="v-middle nowrap text-center">
                                                            Reserva N° {{ reserva.id|default('-') }}
                                                        </td>
                                                        <td class="v-middle nowrap text-center">
                                                            {{ movimiento.fechaCreacion is not null ? movimiento.fechaCreacion|date('d/m/Y') : '-' }}
                                                        </td>
                                                        <td class="v-middle nowrap text-center">
                                                            <a href="{{ path('imprimir_comprobante_movimiento_ticket',{id: movimiento.id}) }}" target="_blank"
                                                               class="btn btn-light-primary btn-icon btn-sm blue" title="Imprimir ticket" style="height: 25px;width: 25px;">
                                                                <i class="fa fa-receipt text-white"></i>
                                                            </a>
                                                        </td>
                                                    </tr>
                                                {% endfor %}
                                            {% endfor %}
                                            {% for pedido in razonSocial.pedidos %}
                                                {% for movimiento in pedido.cuentaCorrientePedido.movimientos %}
                                                    <tr>
                                                        <td class="v-middle nowrap text-center">
                                                            {{ movimiento.monto|money_format }}
                                                        </td>
                                                        <td class="v-middle nowrap text-center">
                                                            {{ movimiento.modoPago|default('-') }}
                                                        </td>
                                                        <td class="v-middle nowrap text-center">
                                                            {{ movimiento.descripcion|default('-') }}
                                                        </td>
                                                        <td class="v-middle nowrap text-center">
                                                            Pedido N° {{ movimiento.pedido.id|default('-') }}
                                                        </td>
                                                        <td class="v-middle nowrap text-center">
                                                            {{ movimiento.fechaCreacion is not null ? movimiento.fechaCreacion|date('d/m/Y') : '-' }}
                                                        </td>
                                                        <td class="v-middle nowrap text-center">
                                                            <a href="{{ path('imprimir_comprobante_movimiento_ticket',{id: movimiento.id}) }}" target="_blank"
                                                               class="btn btn-light-primary btn-icon btn-sm blue" title="Imprimir ticket" style="height: 25px;width: 25px;">
                                                                <i class="fa fa-receipt text-white"></i>
                                                            </a>
                                                        </td>
                                                    </tr>
                                                {% endfor %}
                                            {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                {% else %}
                                    <div class="row row-dictado-empty margin-top-20">
                                        <div class="col-md-12">
                                            <div class="note bg-grey-cararra font-size-13">
                                                El cliente no presenta movimientos.
                                            </div>
                                        </div>
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/situacion_cliente/empresa/show_clientes.html.twig
<div class="card card-detail">
    <div class="card-header d-flex justify-content-between align-items-center padding-10" style="min-height: 54px">
        <div class="card-title mb-0 d-flex align-items-center">
            <h4 class="card-label mb-0">Clientes Razon Social</h4>
        </div>
    </div>
    <div class="card-body padding-20">
        <div class="row">
            <div class="tab-content" style="width: 100%;">
                <div class="tab-pane active" id="portlet_pedido_listado">
                    <div class="portlet-body padding-0">
                        <div class="row">
                            <div class="col-md-12">
                                {% if razonSocial.clientes|length > 0 %}
                                    <div class="table-scrollable" style="border: none;overflow-y:scroll; height:400px;">
                                        <table class="table table-striped table-bordered table-advance table-hover" style="border: 1px solid #ddd;">
                                            <thead>
                                            <tr>
                                                <th class="text-center nowrap">Nombre</th>
                                                <th class="text-center nowrap">Apellido</th>
                                                <th class="text-center nowrap"></th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            {% for cliente in razonSocial.clientes %}
                                                <tr>
                                                    <td class="v-middle nowrap text-center">
                                                        {{ cliente.nombre|default('-') }}
                                                    </td>
                                                    <td class="v-middle nowrap text-center">
                                                        {{ cliente.apellido|default('-') }}
                                                    </td>
                                                    <td class="text-center dt-acciones">
                                                        <div class="dropdown dropdown-inline">
                                                            <button type="button" class="btn btn-light-primary btn-icon btn-sm" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                                <i class="ki ki-bold-more-hor"></i>
                                                            </button>
                                                            <div class="dropdown-menu">
                                                                <a href="{{ path('usuario_show',{id: cliente.id}) }}" class="dropdown-item">
                                                                    <i class="la la-search" style="margin-right: 5px;"></i> Ver Cliente
                                                                </a>
                                                                <a href="{{ path('usuario_edit',{id: cliente.id}) }}" class="dropdown-item">
                                                                    <i class="la la-pencil" style="margin-right: 5px;"></i> Editar Cliente
                                                                </a>
                                                                <a href="{{ path('situacioncliente_show',{id: cliente.id}) }}" class="dropdown-item">
                                                                    <i class="la la-file-pdf" style="margin-right: 5px;"></i> Situacion Cliente
                                                                </a>
                                                            </div>
                                                        </div>
                                                    </td>
                                                </tr>
                                            {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                {% else %}
                                    <div class="row row-dictado-empty margin-top-20">
                                        <div class="col-md-12">
                                            <div class="note bg-grey-cararra font-size-13">
                                                La razon social no tiene clientes.
                                            </div>
                                        </div>
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>