src/Entity/Pedido.php
<?php

namespace App\Entity;

use App\Entity\Traits;
use App\Repository\PedidoRepository;
use App\Entity\Traits\Auditoria;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * Grupo
 *
 * @ORM\Table(name="pedido")
 * @ORM\Entity(repositoryClass=PedidoRepository::class)
 *
 * @Gedmo\SoftDeleteable(fieldName="fechaBaja")
 */
class Pedido {

    use Auditoria;

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    protected $id;

    /**
     * @ORM\OneToMany(targetEntity=PedidoProducto::class, mappedBy="pedido", cascade={"all"})
     * @ORM\OrderBy({"id" = "DESC"})
     */
    private $pedidosProductos;

    /**
     * @ORM\ManyToOne(targetEntity=Usuario::class, inversedBy="pedidos")
     * @ORM\JoinColumn(name="id_cliente", referencedColumnName="id")
     */
    private $cliente;

    /**
     * @ORM\Column(name="observacion", type="string", length=255, nullable=true)
     */
    private $observacion;

    /**
     * @ORM\OneToOne(targetEntity=CuentaCorrientePedido::class, inversedBy="pedido")
     * @ORM\JoinColumn(name="id_cuenta_corriente_pedido", referencedColumnName="id")
     */
    private $cuentaCorrientePedido;

    public function __construct()
    {
        $this->historicoEstados = new ArrayCollection();
        $this->pedidosProductos = new ArrayCollection();
    }

    public function __toString(): string
    {
        return 'Pedido N° '.$this->getId(). ' Fecha Pedido: '.$this->getFechaCreacion()->format('d/m/Y');
    }

    public function getNombreCorto(): string
    {
        return 'Pedido N° '.$this->getId();
    }


    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param int $id
     */
    public function setId(int $id): void
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getPedidosProductos()
    {
        return $this->pedidosProductos;
    }

    /**
     * @param mixed $pedidosProductos
     */
    public function setPedidosProductos($pedidosProductos): void
    {
        $this->pedidosProductos = $pedidosProductos;

        foreach ($pedidosProductos as $pedidoProducto){
            $pedidoProducto->setPedido($this);
        }
    }

    /**
     * @return mixed
     */
    public function addPedidosProductos($pedidoProducto)
    {
        if (!$this->pedidosProductos->contains($pedidoProducto)) {
            $this->pedidosProductos[] = $pedidoProducto;
            $pedidoProducto->setPedido($this);
        }

        return $this;
    }

    /**
     * @return mixed
     */
    public function getCliente()
    {
        return $this->cliente;
    }

    /**
     * @param mixed $cliente
     */
    public function setCliente($cliente): void
    {
        $this->cliente = $cliente;
    }

    /**
     * @return mixed
     */
    public function getHistoricoEstados()
    {
        return $this->historicoEstados;
    }

    /**
     * @param mixed $historicoEstados
     */
    public function setHistoricoEstados($historicoEstados): void
    {
        $this->historicoEstados = $historicoEstados;
    }

    /**
     * @return mixed
     */
    public function getEstado()
    {
        return $this->estado;
    }

    /**
     * @param mixed $estado
     */
    public function setEstado($estado): void
    {
        $this->estado = $estado;
    }



    /**
     * @return mixed
     */
    public function getObservacion()
    {
        return $this->observacion;
    }

    /**
     * @param mixed $observacion
     */
    public function setObservacion($observacion): void
    {
        $this->observacion = $observacion;
    }

    public function addPedidosProducto(PedidoProducto $pedidosProducto): static
    {
        if (!$this->pedidosProductos->contains($pedidosProducto)) {
            $this->pedidosProductos->add($pedidosProducto);
            $pedidosProducto->setPedido($this);
        }

        return $this;
    }

    public function removePedidosProducto(PedidoProducto $pedidosProducto): static
    {
        if ($this->pedidosProductos->removeElement($pedidosProducto)) {
            // set the owning side to null (unless already changed)
            if ($pedidosProducto->getPedido() === $this) {
                $pedidosProducto->setPedido(null);
            }
        }

        return $this;
    }

    /**
     * @return mixed
     */
    public function getCuentaCorrientePedido()
    {
        return $this->cuentaCorrientePedido;
    }

    /**
     * @param mixed $cuentaCorrientePedido
     */
    public function setCuentaCorrientePedido($cuentaCorrientePedido): void
    {
        $this->cuentaCorrientePedido = $cuentaCorrientePedido;
    }

    public function getAdelanto(){
        return $this->getCuentaCorrientePedido()->getSaldo();
    }

    public function getTieneMovimientos(){
        return (sizeof($this->getCuentaCorrientePedido()->getMovimientos()) > 0);
    }

    public function getCodigo(){
        return str_pad($this->id, 6, "0", STR_PAD_LEFT);
    }

}

src/Entity/Remito.php
<?php

namespace App\Entity;

use App\Entity\Traits;
use App\Entity\Traits\Auditoria;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * Grupo
 *
 * @ORM\Table(name="remito")
 * @ORM\Entity
 * @Gedmo\SoftDeleteable(fieldName="fechaBaja")
 */
class Remito {

    use Auditoria;

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    protected $id;

    /**
     * @ORM\ManyToOne(targetEntity=TipoDescuento::class)
     * @ORM\JoinColumn(name="id_tipo_descuento", referencedColumnName="id", nullable=true)
     */
    private $tipoDescuento;

    /**
     * @ORM\Column(name="cantidad_descuento", type="integer", nullable=true)
     */
    private $cantidadDescuento;

    /**
     * @ORM\Column(name="motivo_descuento", type="string", length=255, nullable=true)
     */
    private $motivoDescuento;

    /**
     * @ORM\OneToMany(targetEntity=EstadoRemitoHistorico::class, mappedBy="remito", cascade={"all"})
     * @ORM\OrderBy({"fecha" = "DESC", "id" = "DESC"})
     */
    private $historicoEstados;

    /**
     * @ORM\ManyToOne(targetEntity=EstadoRemito::class)
     * @ORM\JoinColumn(name="id_estado_remito", referencedColumnName="id", nullable=false)
     */
    private mixed $estado;


    /**
     * @ORM\OneToMany(targetEntity=Pago::class, mappedBy="remito", cascade={"all"})
     * @ORM\OrderBy({"fechaCreacion" = "ASC"})
     */
    private $pagos;

    /**
     * @ORM\OneToMany(targetEntity=Entrega::class, mappedBy="remito", cascade={"all"})
     * @ORM\OrderBy({"id" = "DESC"})
     */
    private $entregas;

    /**
     * @ORM\ManyToOne(targetEntity=Usuario::class, inversedBy="remitos")
     * @ORM\JoinColumn(name="id_cliente", referencedColumnName="id", nullable=false)
     */
    private $cliente;

    /**
     * @ORM\Column(name="saldo_cuenta_corriente", type="decimal", precision=10, scale=2, nullable=true)
     */
    private $saldoCuentaCorriente;

    /**
     * @ORM\Column(name="total_deuda", type="decimal", precision=10, scale=2, nullable=true)
     */
    private $totalDeuda;

    public function __construct()
    {
        $this->entregas = new ArrayCollection();
        $this->historicoEstados = new ArrayCollection();
        $this->pagos = new ArrayCollection();
    }

    public function __toString(): string
    {
        return 'Remito N° '.$this->getId();
    }


    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    public function getCodigo(){
        return str_pad($this->id, 6, "0", STR_PAD_LEFT);
    }

    /**
     * @param int $id
     */
    public function setId(int $id): void
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getCliente()
    {
        return $this->cliente;
    }

    /**
     * @param mixed $cliente
     */
    public function setCliente($cliente): void
    {
        $this->cliente = $cliente;
    }

    public function getTotalSinDescuento(){
        $total = 0.00;
        foreach ($this->getEntregas() as $entrega) {
            foreach ($entrega->getEntregasProductos() as $entregaProducto) {
                $total += $entregaProducto->getPrecioSubTotal();
            }
        }
        return $total;
    }

    public function getTotalConDescuento(){
        $total = $this->getTotalSinDescuento();
        if ($this->getTipoDescuento() != null) {
            switch ($this->getTipoDescuento()->getCodigoInterno()) {
                case 1:
                    $total -= $this->getCantidadDescuento();
                    break;
                case 2:
                    $total -= (($total * $this->getCantidadDescuento()) / 100);
                    break;
            }
        }
        return $total;
    }

    public function getMontoDescuento($totalSinDescuento = null){
        $totalSinDescuento = ($totalSinDescuento == null ? $this->getTotalSinDescuento() : $totalSinDescuento);
        $descuento = '';
        if ($this->getTipoDescuento() != null) {
            switch ($this->getTipoDescuento()->getCodigoInterno()) {
                case 1:
                    $descuento = $this->getCantidadDescuento();
                    break;
                case 2:
                    $descuento = (($totalSinDescuento * $this->getCantidadDescuento()) / 100);
                    break;
            }
        }

        return $descuento;
    }

    public function getTipoDescuentoString(){
        $tipoDescuento = '';
        if ($this->getTipoDescuento() != null) {
            switch ($this->getTipoDescuento()->getCodigoInterno()) {
                case 1:
                    $tipoDescuento = '-';
                    break;
                case 2:
                    $tipoDescuento = '('.$this->getCantidadDescuento().'%) -';
                    break;
            }
        }

        return $tipoDescuento;
    }

    /**
     * @return mixed
     */
    public function getTipoDescuento()
    {
        return $this->tipoDescuento;
    }

    /**
     * @param mixed $tipoDescuento
     */
    public function setTipoDescuento($tipoDescuento): void
    {
        $this->tipoDescuento = $tipoDescuento;
    }

    /**
     * @return mixed
     */
    public function getCantidadDescuento()
    {
        return $this->cantidadDescuento;
    }

    /**
     * @param mixed $cantidadDescuento
     */
    public function setCantidadDescuento($cantidadDescuento): void
    {
        $this->cantidadDescuento = $cantidadDescuento;
        /*if ($this->getTipoDescuento() != null) {
            if ($this->getTipoDescuento()->getCodigoInterno() == 1) {
                $cantidadDescuento = $this->getCantidadDescuento();
                foreach ($this->getEntregas() as $entrega) {
                    foreach ($entrega->getEntregasProductos() as $entregaProducto) {
                        if ($cantidadDescuento > 0) {
                            $descontar = $cantidadDescuento >= $entregaProducto->getPrecioSubTotal() ? $entregaProducto->getPrecioSubTotal() : $cantidadDescuento;
                            $entregaProducto->setCantidadDescuentoFijo($descontar);
                            $cantidadDescuento -= $descontar;
                        }
                    }
                }
            }
        }*/
    }

    /**
     * @return string|null
     */
    public function getMotivoDescuento(): ?string
    {
        return $this->motivoDescuento;
    }

    /**
     * @param string|null $motivoDescuento
     * @return $this
     */
    public function setMotivoDescuento(?string $motivoDescuento): self
    {
        $this->motivoDescuento = $motivoDescuento;
        return $this;
    }

    /**
     * @return Collection|EstadoRemitoHistorico[]
     */
    public function getHistoricoEstados(): Collection
    {
        return $this->historicoEstados;
    }

    /**
     * @param mixed $historicoEstados
     */
    public function setHistoricoEstados($historicoEstados): void
    {
        $this->historicoEstados = $historicoEstados;
    }

    public function getEstado(): mixed
    {
        return $this->estado;
    }

    public function setEstado(mixed $estado): void
    {
        $this->estado = $estado;
    }

    public function addHistoricoEstado(EstadoRemitoHistorico $historicoEstado): self {
        if (!$this->historicoEstados->contains($historicoEstado)) {
            $this->historicoEstados[] = $historicoEstado;
            $historicoEstado->setRemito($this);
        }

        return $this;
    }

    public function removeHistoricoEstado(EstadoRemitoHistorico $historicoEstado): self {
        if ($this->historicoEstados->removeElement($historicoEstado)) {
            // set the owning side to null (unless already changed)
            if ($historicoEstado->getRemito() === $this) {
                $historicoEstado->setRemito(null);
            }
        }

        return $this;
    }

    public function getPagos()
    {
        return $this->pagos;
    }

    public function setPagos(ArrayCollection $pagos): void
    {
        $this->pagos = $pagos;
    }

    /**
     * @return mixed
     */
    public function addPago(Pago $pago)
    {
        if (!$this->pagos->contains($pago)) {
            $this->pagos[] = $pago;
            $pago->setRemito($this);
        }

        return $this;
    }

    /**
     * @return mixed
     */
    public function getPendiente()
    {
        $pendiente = $this->getTotalConDescuento();
        foreach ($this->pagos as $pago) {
            $pendiente -=$pago->getMonto();
        }
        return $pendiente;
    }

    public function addEntrega(Entrega $entrega): self {
        if (!$this->entregas->contains($entrega)) {
            $this->entregas[] = $entrega;
            $entrega->setRemito($this);
        }

        return $this;
    }

    public function removeEntrega(Entrega $entrega): self {
        if ($this->entregas->removeElement($entrega)) {
            // set the owning side to null (unless already changed)
            if ($entrega->getRemito() === $this) {
                $entrega->setRemito(null);
            }
        }

        return $this;
    }

    /**
     * @return mixed
     */
    public function getEntregas()
    {
        return $this->entregas;
    }

    public function getAdelanto()
    {
        $adelanto = 0;
        $pedidosVistos = [];

        foreach ($this->entregas as $entrega) {
            foreach ($entrega->getEntregasProductos() as $entregaProducto) {
                $pedido = $entregaProducto->getPedidoProducto()->getPedido();
                $pedidoId = $pedido->getId();

                if (!isset($pedidosVistos[$pedidoId])) {
                    $adelanto += $pedido->getAdelanto();
                    $pedidosVistos[$pedidoId] = true;
                }
            }
        }

templates/PDF/cliente.html.twig
<div class="table-border header">
    <table width="100%" border="0">
        <tr>
            <td>
                <table cellpadding="5" cellspacing="5" style="padding: 0;">
                    <tr>
                        <td align="right"><strong>NOMBRE</strong></td>
                        <td>{{ entity.cliente.nombreCompleto|default('-') }}</td>
                        <td align="right"><strong>CUIT</strong></td>
                        <td>{{ entity.cliente.cuit|default('-') }}</td>
                    </tr>
                    <tr>
                        <td align="right"><strong>CELULAR</strong></td>
                        <td>{{ entity.cliente.celular|default('-') }}</td>
                        <td align="right"><strong>DOMICILIO</strong></td>
                        <td>{{ entity.cliente.domicilio|default('-') }}</td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</div>

templates/PDF/confirmar.css.twig
.remito{
    font-size: 14px;
    font-family: monospace;
}
.datos-header{
    max-width: 100%;
}
.logo-empresa{
    margin-top: 40px;
    margin-left: 10px;
}
.header-entrega-left{
    border: 2px solid;
    border-radius: 5px;
}
.header-entrega-right{
    border: 2px solid;
    border-radius: 5px;
}
.datos-empresa{
    margin-top: 16px;
    line-height: 3mm;
}
.datos-entrega{
    margin-top: 24px;
    line-height: 7.3mm;
    font-size: 20px;
}
.entrega-title{
    text-align: center;
}
.entrega-datos{
    text-align: right;
}
.datos-cliente{
    border: 2px solid;
    border-radius: 5px;
    margin-top: 10px;
    max-width: 100%;
    font-size: 18px;
}
.datos-productos{
    margin-top: 10px;
    padding: 0px;
}

.datos-productos-table{
    margin: 0px;
    font-size: 18px;
    width: 98%;
}

templates/PDF/confirmar_body.html.twig
<div class="row">
    <div class="col-md-12 datos-productos">
        <table class="datos-productos-table" border="2" cellpadding="5" cellspacing="0" align="center">
            <thead>
            <tr style="background-color: gainsboro;">
                <th class="text-center">N° ORDEN</th>
                <th class="text-center">PRODUCTO</th>
                <th class="text-center">CANTIDAD</th>
                <th class="text-center">PRECIO U.</th>
                <th class="text-center">SUBTOTAL</th>
                <th class="text-center">DESCUENTO</th>
            </tr>
            </thead>
            <tbody>
                {% for e in entrega %}
                    {% for entregaProducto in e.entregasProductos %}
                        <tr>
                            <td width="170" align="center">{{ entregaProducto.pedidoProducto.numeroOrdenCompleto }}</td>
                            <td width="395" align="center">{{ entregaProducto.pedidoProducto.productoBandeja }}</td>
                            <td width="144" align="center">{{ entregaProducto.cantidadBandejas }}</td>
                            <td width="157" align="center">{{ entregaProducto.precioUnitario|money_format }}</td>
                            <td width="183" align="right">{{ entregaProducto.precioSubTotal|money_format }}</td>
                            <td width="183" align="right">{{ entregaProducto.montoDescuento(entregaProducto.precioSubTotal, remito)|money_format|default('-') }}</td>
                        </tr>
                    {% endfor %}
                {% endfor %}
            </tbody>
            <tfoot>
            <tr>
                <th colspan="4" style="text-align: right; font-size: 18px">
                    {% if remito.adelanto > 0 %}
                        ADELANTO<br>
                    {% endif %}
                    {% if remito.tipoDescuento != null %}
                        SUBTOTAL <br>
                        {{ remito.tipoDescuento }} <br>
                    {% endif %}
                    TOTAL
                </th>
                <td align="right" colspan="2">
                    {% if remito.adelanto > 0 %}
                        {{ adelanto|money_format }} <br>
                    {% endif %}
                    {% if remito.tipoDescuento != null %}
                        {{ totalSinDescuento|money_format }}<br>
                        {{ remito.tipoDescuentoString }}{{ remito.montoDescuento(totalSinDescuento)|money_format }} <br>
                    {% endif %}
                    {{ total|money_format }}
                </td>
            </tr>
            </tfoot>
        </table>
    </div>
</div>

templates/PDF/confirmar_header.html.twig
<div class="row datos-header">
    <div class="col-md-8 header-entrega-left">
        <div class="row">
            <div class="col-md-5 logo-empresa"><img src="{{ asset('images/logo/logo.png') }}" alt="logo" width="200" height="100"></div>
            <div class="col-md-6 datos-empresa">
                <div class="row">
                    <div class="col-md-5">
                        <p><strong>RAZÓN SOCIAL</strong></p>
                        <p><strong>CUIT</strong> </p>
                        <p><strong>WEB</strong> </p>
                        <p><strong>DIRECCIÓN</strong></p>
                        <p><strong>LOCALIDAD</strong></p>
                        <p><strong>TELÉFONO</strong></p>
                    </div>
                    <div class="col-md-6">
                        <p> Baby Plant srl</p>
                        <p> 33-71230651-9</p>
                        <p> www.babyplant.com.ar</p>
                        <p> 44 4303</p>
                        <p> Lis. Olmos la Plata</p>
                        <p> 0221 15-669-0199</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="offset-md-1 col-md-3 header-entrega-right">
        <div class="col-md-12 datos-entrega">
            <div class="row">
                <div class="col-md-12">
                    <h1 class="entrega-title">REMITO</h1>
                </div>
                <div class="col-md-5 entrega-datos">
                    <p><strong>N°</strong></p>
                    <p><strong>FECHA</strong> </p>
                </div>
                <div class="col-md-6">
                    <p>{{ remito.codigo }}</p>
                    <p>{{ remito.fechaCreacion|date('d/m/Y') }}</p>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row datos-cliente">
    <div class="col-md-12" style="padding-top: 10px;">
        <div class="row">
            <div class="offset-md-1 col-md-5">
                <div class="row">
                    <div class="col-md-6" style="text-align: right">
                        <p><strong>CLIENTE</strong></p>
                        <p><strong>CUIT</strong> </p>
                    </div>
                    <div class="col-md-6">
                        <p>{{ remito.cliente.nombreCompleto|default('-') }}</p>
                        <p>{{ remito.cliente.cuit|default('-') }}</p>
                    </div>
                </div>

            </div>
            <div class="col-md-5">
                <div class="row">
                    <div class="col-md-6" style="text-align: right">
                        <p><strong>TELÉFONO</strong></p>
                        <p><strong>DIRECCION</strong></p>
                    </div>
                    <div class="col-md-6">
                        <p>{{ remito.cliente.celular|default('') }}</p>
                        <p>{{ remito.cliente.domicilio|default('-') }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/PDF/default.css.twig
<style type="text/css">
    * {
    font-size: 11px;
    }

body {
    font-family: 'Verdana';
    margin: 0;
    padding: 0;
}

@page {
    header: default_header;
    footer: default_footer;
    margin-header: 5mm;
}

.page {
    position: relative;
    page-break-after: always;
    height: 360mm;
    width: 100%;
}

table {
    border-collapse: collapse;
    border-left: none;
    margin-top: -1px;
}

td{
    padding: 4px 2px;
}

td.header{
    padding: 2px;
    border-collapse: collapse;
}

.bold{
    font-weight: bold;
}
.b-none{
    border-top: none;
    border-bottom: none;
    border-left: none;
    border-right: none;
}
.b-bottom{ border-bottom: 1px solid black;}
.b-top{ border-top: 1px solid #000;}

.b-bottom-none{
    border-bottom: none;
}

.b-top-none{
    border-top: none;
}

.padding{
    padding: 4px 2px;
}

.f-8{ font-size: 7px; }
.f-9{ font-size: 8px; }
.f-10{ font-size: 9px; }
.f-12{ font-size: 11px; }
.f-14{ font-size: 13px; }
.f-18{ font-size: 17px; }
.f-20{ font-size: 19px; }
.f-25{ font-size: 24px; }

.t-left{ text-align: left; }
.t-right{ text-align: right; }
.t-center{ text-align: center; }
.t-justify{ text-align: justify; }

.w-5{ width: 5% }
.w-10{ width: 10% }
.w-12{ width: 12.5% }
.w-15{ width: 15% }
.w-20{ width: 20%; }
.w-25{ width: 25%; }
.w-30{ width: 30%; }
.w-35{ width: 35%; }
.w-40{ width: 40%; }
.w-50{ width: 50%; }
.w-60{ width: 60%; }
.w-75{ width: 75%; }
.w-85{ width: 85%; }
.w-100{ width: 100%; }

.h-5 { height: 5mm; }
.h-10{ height: 10mm; }
.h-15{ height: 15mm; }
.h-20{ height: 20mm; }
.h-25{ height: 25mm; }
.h-30{ height: 30mm; }

.m-top{
    margin-top: 5mm;
}

.m-top-2-5{
    margin-top: 2.5mm;
}

.m-left-10{
    margin-left: 10%;
}

.hlt{
    background-color: #EEE;
    font-weight: bold;
}

.hlt2{
    background-color: #DDD;
    font-weight: bold;
}

span.clear{
    float: left;
    clear: both;
    display: inline-block;
}

.monospc {
    font-family: 'Courier new';
    font-size: 12px;
}

.concepto td{
    border: 0;
    border-left:1px solid #000;
    border-right: 1px solid #000;
}

.v-align-top, .v-align-top td {
    vertical-align: top;
}

.v-align-bottom, .v-align-bottom td {
    vertical-align: bottom;
}

.v-align-middle, .v-align-middle td {
    vertical-align: middle;
}

.linea-firma{
    border-bottom: 1px solid #FFF;
}

.borderless{
    border-bottom: 1px solid white;
    border-right: 1px solid white;
    border-left: 1px solid white;
}

.only-bottom-border{
    border-bottom: 1px solid black;
}

.underline {
    text-decoration: underline;
}

.p-top-150 {
    padding-top: 150px;
}

</style>

templates/PDF/header.html.twig
<div class="table-border header">
    <table width="100%" border="0">
        <tr>
            <td>
                <img src="{{ asset('images/logo/logo.png') }}" width="45mm" height="20mm">
            </td>

            <td>
                <table cellpadding="3" cellspacing="0" style="padding: 0;">
                    <tr>
                        <td align="right"><strong>RAZÓN SOCIAL</strong></td>
                        <td>Baby Plant srl</td>
                    </tr>
                    <tr>
                        <td align="right"><strong>CUIT</strong></td>
                        <td>33-71230651-9</td>
                    </tr>
                    <tr>
                        <td align="right"><strong>WEB</strong></td>
                        <td>www.babyplant.com.ar</td>
                    </tr>
                    <tr>
                        <td align="right"><strong>DIRECCIÓN</strong></td>
                        <td>44 4303</td>
                    </tr>
                    <tr>
                        <td align="right"><strong>LOCALIDAD</strong></td>
                        <td>Lis. Olmos la Plata</td>
                    </tr>
                    <tr>
                        <td align="right"><strong>TELÉFONO</strong></td>
                        <td>0221 15-669-0199</td>
                    </tr>
                </table>
            </td>

            <td>
                <table cellpadding="3" cellspacing="10">
                    <tr>
                        <td align="left" colspan="2" style="font-size: 30px"><strong>{{ tipo_pdf|default('') }}</strong></td>
                    </tr>
                    <tr>
                        <td align="right"><strong>N°</strong></td>
                        <td>{{ entity.codigo|default(entity.id) }}</td>
                    </tr>
                    <tr>
                        <td align="right"><strong>FECHA</strong></td>
                        <td>{{ entity.fechaCreacion|date('d/m/Y') }}</td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</div>

templates/PDF/header_interno.html.twig
<div class="table-border header">
    <table width="100%" border="0">
        <tr>
            <td>
                <img src="{{ asset('images/logo/logo.png') }}" width="45mm" height="20mm">
            </td>

            <td>
                <table cellpadding="3" cellspacing="10">
                    <tr>
                        <td align="center" colspan="2" style="font-size: 30px"><strong>{{ tipo_pdf|default('') }}</strong></td>
                    </tr>
                    <tr>
                        <td align="right"><strong>N°</strong></td>
                        <td>{{ entity.codigo|default(entity.id) }}</td>
                    </tr>
                    <tr>
                        <td align="right"><strong>FECHA</strong></td>
                        <td>{{ entity.fechaCreacion|date('d/m/Y') }}</td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</div>

templates/PDF/header_interno_ticket.html.twig
<div class="table-border header">
    <table width="100%" style="text-align: center;">
        <tr>
            <td>
                <table cellpadding="3" cellspacing="10">
                    <tr>
                        <td colspan="2"><strong>{{ tipo_pdf|default('') }}</strong></td>
                    </tr>
                    <tr>
                        <td align="right"><strong>N°</strong></td>
                        <td align="left">{{ entity.codigo|default(entity.id) }}}</td>
                    </tr>
                    <tr>
                        <td align="right"><strong>FECHA</strong></td>
                        <td align="left">{{ entity.fechaCreacion|date('d/m/Y') }}</td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</div>